---
- name: List installed packages
  hosts: rhel
  tasks:
    - name: List installed packages
      ansible.builtin.package_facts:
        manager: auto
    - name: Print the list of installed packages
      ansible.builtin.debug:
        var: ansible_facts['packages']
